import { VehicleReportItem } from '../types';

// These shapes used to live in the (now deleted) VehicleAreaAssignmentView
// component, which was never rendered. They are kept here because the live
// ReportsView / CommissionerConsole assignment data still uses them.
export interface VehicleOption {
  id: string;
  name: string;
  type: string;
  capacity: string;
  colorHex: string;
  colorName: string;
  imageUrl?: string;
  bgGradient: string;
  cardBorder: string;
  cardBg: string;
  iconBg: string;
  iconColor: string;
  titleColor: string;
  textColor: string;
  dotColor: string;
  activeRing: string;
  shadowColor: string;
}

export interface AreaOption {
  id: string;
  name: string;
  nameTa?: string;
  zone?: string;
  ward?: string;
  streets?: string[];
  streetsCount: number;
  qrPoints: number;
  assignedVehicleId?: string;
  assignedVehicleName?: string;
  assignedColorHex?: string;
  assignedBgColor?: string;
}

export const VEHICLE_ASSIGNMENT_STORAGE_KEY = 'ccmc_vehicle_area_assignments';
export const VEHICLE_ASSIGNMENT_EVENT = 'ccmc-vehicle-assignments-updated';

export interface VehicleMasterInfo {
  id: string;
  name: string;
  type: string;
  plateNo: string;
  capacity: string;
  driverName: string;
  driverPhone: string;
  shiftTiming: string;
  colorHex: string;
  colorName: string;
  imageUrl?: string;
  gpsStatus: string;
  speed: string;
  batteryOrFuel: string;
  tripsToDumpYard: number;
  status: 'In Service' | 'On Route' | 'Standby' | 'Maintenance';
}


/**
 * Transform assigned areas into VehicleReportItem format for ReportsView
 */
export const REAL_QR_VEHICLE_REPORTS: VehicleReportItem[] = [
  {
    id: 'vr-1',
    vehicleNo: 'TN66AE6121',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'murali',
    driverPhone: '9677971375',
    zone: 'East Zone',
    ward: 'Ward 24',
    assignedWards: ['Ward 24'],
    assignedStreets: ['sree nagar'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 140,
    coveredHouseholds: 140,
    coveragePercentage: 100,
    distanceCoveredKm: 14.2,
    tripsToDumpYard: 2,
    totalPayloadTons: 1.4,
    fuelOrBattery: 85,
    gpsStatus: 'GPS Live (14 km/h)',
    status: 'In Service',
    siName: 'S.R.GERALD SATHIYA PUNITHAN',
    siPhone: '9442504589',
    ssName: 'vibin',
    ssPhone: '9442504589',
    cssName: 'vengatesh',
    cssPhone: '8072092485',
  },
  {
    id: 'vr-2',
    vehicleNo: 'TN66AD6465',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'YOGARAJ',
    driverPhone: '8220110220',
    zone: 'East Zone',
    ward: 'Ward 24',
    assignedWards: ['Ward 24'],
    assignedStreets: ['MAGESHWARI NAGAR'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 30,
    coveredHouseholds: 30,
    coveragePercentage: 100,
    distanceCoveredKm: 8.5,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.8,
    fuelOrBattery: 90,
    gpsStatus: 'GPS Live (12 km/h)',
    status: 'In Service',
    siName: 'S.R.GERALD SATHIYA PUNITHAN',
    siPhone: '9442504589',
    ssName: 'vibin',
    ssPhone: '9442504589',
    cssName: 'vengatesh',
    cssPhone: '8072092485',
  },
  {
    id: 'vr-3',
    vehicleNo: 'PUSHCART',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'SUSILA',
    driverPhone: '9790598785',
    zone: 'East Zone',
    ward: 'Ward 24',
    assignedWards: ['Ward 24'],
    assignedStreets: ['THIYAGIKUMAR STREET'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 211,
    coveredHouseholds: 211,
    coveragePercentage: 100,
    distanceCoveredKm: 4.0,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.2,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'S.R.GERALD SATHIYA PUNITHAN',
    siPhone: '9442504589',
    ssName: 'vibin',
    ssPhone: '9442504589',
    cssName: 'vengatesh',
    cssPhone: '8072092485',
  },
  {
    id: 'vr-4',
    vehicleNo: 'PUSHCART2',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'PRIYA',
    driverPhone: '7397587127',
    zone: 'East Zone',
    ward: 'Ward 24',
    assignedWards: ['Ward 24'],
    assignedStreets: ['M.G.R.VEEDHI'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 95,
    coveredHouseholds: 95,
    coveragePercentage: 100,
    distanceCoveredKm: 3.5,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.15,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'S.R.GERALD SATHIYA PUNITHAN',
    siPhone: '9442504589',
    ssName: 'vibin',
    ssPhone: '9442504589',
    cssName: 'vengatesh',
    cssPhone: '8072092485',
  },
  {
    id: 'vr-5',
    vehicleNo: 'BOV',
    type: 'BOV (Battery Operated Vehicle)',
    capacity: '600 kg',
    driverName: 'ANADHAN',
    driverPhone: '8098347628',
    zone: 'East Zone',
    ward: 'Ward 24',
    assignedWards: ['Ward 24'],
    assignedStreets: ['KALYANAM SUNDHARAM STREET'],
    shiftTiming: '06:30 AM - 02:30 PM',
    targetHouseholds: 700,
    coveredHouseholds: 700,
    coveragePercentage: 100,
    distanceCoveredKm: 12.0,
    tripsToDumpYard: 2,
    totalPayloadTons: 0.7,
    fuelOrBattery: 88,
    gpsStatus: 'GPS Live (8 km/h)',
    status: 'In Service',
    siName: 'S.R.GERALD SATHIYA PUNITHAN',
    siPhone: '9442504589',
    ssName: 'vibin',
    ssPhone: '9442504589',
    cssName: 'vengatesh',
    cssPhone: '8072092485',
  },
  {
    id: 'vr-6',
    vehicleNo: 'TN66AD8373',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'surya',
    driverPhone: '8870418209',
    zone: 'Central Zone',
    ward: 'Ward 49',
    assignedWards: ['Ward 49'],
    assignedStreets: ['ponni nagar'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 530,
    coveredHouseholds: 530,
    coveragePercentage: 100,
    distanceCoveredKm: 16.5,
    tripsToDumpYard: 2,
    totalPayloadTons: 1.8,
    fuelOrBattery: 78,
    gpsStatus: 'GPS Live (15 km/h)',
    status: 'In Service',
    siName: 'LOGANATHAN',
    siPhone: '9489206052',
    ssName: 'MUTHUSAMY',
    ssPhone: '9442104143',
    cssName: 'YAMUNA',
    cssPhone: '6385728557',
  },
  {
    id: 'vr-7',
    vehicleNo: 'TN66AQ1114',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'GOKULA KRISHNAN',
    driverPhone: '9751099379',
    zone: 'Central Zone',
    ward: 'Ward 49',
    assignedWards: ['Ward 49'],
    assignedStreets: ['ponni nagar'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 250,
    coveredHouseholds: 250,
    coveragePercentage: 100,
    distanceCoveredKm: 11.2,
    tripsToDumpYard: 2,
    totalPayloadTons: 1.2,
    fuelOrBattery: 82,
    gpsStatus: 'GPS Live (16 km/h)',
    status: 'In Service',
    siName: 'LOGANATHAN',
    siPhone: '9489206052',
    ssName: 'MUTHUSAMY',
    ssPhone: '9442104143',
    cssName: 'YAMUNA',
    cssPhone: '6385728557',
  },
  {
    id: 'vr-8',
    vehicleNo: 'PUSHCART3',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'PALANISAMY',
    driverPhone: '9677966465',
    zone: 'Central Zone',
    ward: 'Ward 49',
    assignedWards: ['Ward 49'],
    assignedStreets: ['KANDHASAMY LAYOUT'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 250,
    coveredHouseholds: 250,
    coveragePercentage: 100,
    distanceCoveredKm: 4.5,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.25,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'LOGANATHAN',
    siPhone: '9489206052',
    ssName: 'MUTHUSAMY',
    ssPhone: '9442104143',
    cssName: 'YAMUNA',
    cssPhone: '6385728557',
  },
  {
    id: 'vr-9',
    vehicleNo: 'PUSHCART4',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'VADIVUKARASI',
    driverPhone: '7667769132',
    zone: 'Central Zone',
    ward: 'Ward 49',
    assignedWards: ['Ward 49'],
    assignedStreets: ['LAKSHMI MILLS SIGNAL'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 250,
    coveredHouseholds: 250,
    coveragePercentage: 100,
    distanceCoveredKm: 4.2,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.25,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'LOGANATHAN',
    siPhone: '9489206052',
    ssName: 'MUTHUSAMY',
    ssPhone: '9442104143',
    cssName: 'YAMUNA',
    cssPhone: '6385728557',
  },
  {
    id: 'vr-10',
    vehicleNo: 'TN66AQ0794',
    type: 'BOV (Battery Operated Vehicle)',
    capacity: '600 kg',
    driverName: 'UDHAYAKUMAR',
    driverPhone: '8056960451',
    zone: 'Central Zone',
    ward: 'Ward 49',
    assignedWards: ['Ward 49'],
    assignedStreets: ['MARIYAMMAN KOVIL STREET'],
    shiftTiming: '06:30 AM - 02:30 PM',
    targetHouseholds: 215,
    coveredHouseholds: 215,
    coveragePercentage: 100,
    distanceCoveredKm: 9.8,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.3,
    fuelOrBattery: 85,
    gpsStatus: 'GPS Live (9 km/h)',
    status: 'In Service',
    siName: 'LOGANATHAN',
    siPhone: '9489206052',
    ssName: 'MUTHUSAMY',
    ssPhone: '9442104143',
    cssName: 'YAMUNA',
    cssPhone: '6385728557',
  },
  {
    id: 'vr-11',
    vehicleNo: 'TN66AQ1287',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'SARAVANA KUMAR',
    driverPhone: '9750545466',
    zone: 'West Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['KK NAGAR'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 24,
    coveredHouseholds: 24,
    coveragePercentage: 100,
    distanceCoveredKm: 7.5,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.4,
    fuelOrBattery: 92,
    gpsStatus: 'GPS Live (12 km/h)',
    status: 'In Service',
    siName: 'RAJENDRAN',
    siPhone: '8925968002',
    ssName: 'ANANDH',
    ssPhone: '8925968018',
    cssName: 'BALACHANDAR',
    cssPhone: '9043130350',
  },
  {
    id: 'vr-12',
    vehicleNo: 'TN66AC9176',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'SENRAJ',
    driverPhone: '8489034317',
    zone: 'West Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['RANGANATHAN KOVIL STREET'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 45,
    coveredHouseholds: 45,
    coveragePercentage: 100,
    distanceCoveredKm: 8.2,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.5,
    fuelOrBattery: 89,
    gpsStatus: 'GPS Live (14 km/h)',
    status: 'In Service',
    siName: 'RAJENDRAN',
    siPhone: '8925968002',
    ssName: 'ANANDH',
    ssPhone: '8925968018',
    cssName: 'BALACHANDAR',
    cssPhone: '9043130350',
  },
  {
    id: 'vr-13',
    vehicleNo: 'PUSHCART5',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'JOTHI MANI',
    driverPhone: 'N/A',
    zone: 'West Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['BAJANA KOVIL VEEDHI'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 20,
    coveredHouseholds: 20,
    coveragePercentage: 100,
    distanceCoveredKm: 2.5,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.05,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'RAJENDRAN',
    siPhone: '8925968002',
    ssName: 'ANANDH',
    ssPhone: '8925968018',
    cssName: 'BALACHANDAR',
    cssPhone: '9043130350',
  },
  {
    id: 'vr-14',
    vehicleNo: 'PUSHCART6',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'MARAGADHAM',
    driverPhone: '9047038346',
    zone: 'West Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['BAARI NAGAR VEEDHI CUT ROAD'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 18,
    coveredHouseholds: 18,
    coveragePercentage: 100,
    distanceCoveredKm: 2.2,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.05,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'RAJENDRAN',
    siPhone: '8925968002',
    ssName: 'ANANDH',
    ssPhone: '8925968018',
    cssName: 'BALACHANDAR',
    cssPhone: '9043130350',
  },
  {
    id: 'vr-15',
    vehicleNo: 'TN66AP1181',
    type: 'BOV (Battery Operated Vehicle)',
    capacity: '600 kg',
    driverName: 'RAMKUMAR',
    driverPhone: '7317634144',
    zone: 'West Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['RAMASAMY KOONARCUT ROAD'],
    shiftTiming: '06:30 AM - 02:30 PM',
    targetHouseholds: 9,
    coveredHouseholds: 9,
    coveragePercentage: 100,
    distanceCoveredKm: 5.0,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.03,
    fuelOrBattery: 95,
    gpsStatus: 'GPS Live (8 km/h)',
    status: 'In Service',
    siName: 'RAJENDRAN',
    siPhone: '8925968002',
    ssName: 'ANANDH',
    ssPhone: '8925968018',
    cssName: 'BALACHANDAR',
    cssPhone: '9043130350',
  },
  {
    id: 'vr-16',
    vehicleNo: 'TN66AC1906',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'ARUNACHALAM',
    driverPhone: '7317634144',
    zone: 'North Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['MADHURA ENCLAVE', 'SENTHOORA PURAM'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 29,
    coveredHouseholds: 29,
    coveragePercentage: 100,
    distanceCoveredKm: 9.0,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.4,
    fuelOrBattery: 88,
    gpsStatus: 'GPS Live (13 km/h)',
    status: 'In Service',
    siName: 'DHANABALAN',
    siPhone: '9442104133',
    ssName: 'SARAVANA KUMAR',
    ssPhone: '8925968035',
    cssName: 'MURALI',
    cssPhone: '8870591470',
  },
  {
    id: 'vr-17',
    vehicleNo: 'PUSHCART7',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'MUTHULAKSHMI',
    driverPhone: '9786741096',
    zone: 'North Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['MEENAKSHI NAGAR,SMP ESTATE'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 33,
    coveredHouseholds: 33,
    coveragePercentage: 100,
    distanceCoveredKm: 3.0,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.1,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'DHANABALAN',
    siPhone: '9442104133',
    ssName: 'SARAVANA KUMAR',
    ssPhone: '8925968035',
    cssName: 'MURALI',
    cssPhone: '8870591470',
  },
  {
    id: 'vr-18',
    vehicleNo: 'PUSHCART8',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'LATHA',
    driverPhone: '8148654687',
    zone: 'North Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['VISAGA GARDEN'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 19,
    coveredHouseholds: 19,
    coveragePercentage: 100,
    distanceCoveredKm: 2.8,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.05,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'DHANABALAN',
    siPhone: '9442104133',
    ssName: 'SARAVANA KUMAR',
    ssPhone: '8925968035',
    cssName: 'MURALI',
    cssPhone: '8870591470',
  },
  {
    id: 'vr-19',
    vehicleNo: 'TN66AP0965',
    type: 'BOV (Battery Operated Vehicle)',
    capacity: '600 kg',
    driverName: 'PANEERSELVAM',
    driverPhone: '9894051660',
    zone: 'North Zone',
    ward: 'Ward 35',
    assignedWards: ['Ward 35'],
    assignedStreets: ['MARUTHI ENVUE'],
    shiftTiming: '06:30 AM - 02:30 PM',
    targetHouseholds: 25,
    coveredHouseholds: 25,
    coveragePercentage: 100,
    distanceCoveredKm: 6.5,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.1,
    fuelOrBattery: 90,
    gpsStatus: 'GPS Live (10 km/h)',
    status: 'In Service',
    siName: 'DHANABALAN',
    siPhone: '9442104133',
    ssName: 'SARAVANA KUMAR',
    ssPhone: '8925968035',
    cssName: 'MURALI',
    cssPhone: '8870591470',
  },
  {
    id: 'vr-20',
    vehicleNo: 'TN66AM0219',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'KARTHIK',
    driverPhone: '9080463024',
    zone: 'South Zone',
    ward: 'Ward 88',
    assignedWards: ['Ward 88'],
    assignedStreets: ['PALANI AANDAVAR KOVIL VEEDHI'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 762,
    coveredHouseholds: 762,
    coveragePercentage: 100,
    distanceCoveredKm: 18.5,
    tripsToDumpYard: 3,
    totalPayloadTons: 2.2,
    fuelOrBattery: 80,
    gpsStatus: 'GPS Live (15 km/h)',
    status: 'In Service',
    siName: 'ZAHEER HUSSAIN',
    siPhone: '7339404132',
    ssName: 'MUTHURAJ',
    ssPhone: '8925975896',
    cssName: 'GURUMOORTHY',
    cssPhone: '8903593614',
  },
  {
    id: 'vr-21',
    vehicleNo: 'TN66AQ1153',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'SELVARAJ',
    driverPhone: '9361613970',
    zone: 'South Zone',
    ward: 'Ward 88',
    assignedWards: ['Ward 88'],
    assignedStreets: ['KGK MAIN ROAD'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 727,
    coveredHouseholds: 727,
    coveragePercentage: 100,
    distanceCoveredKm: 17.8,
    tripsToDumpYard: 3,
    totalPayloadTons: 2.0,
    fuelOrBattery: 85,
    gpsStatus: 'GPS Live (16 km/h)',
    status: 'In Service',
    siName: 'ZAHEER HUSSAIN',
    siPhone: '7339404132',
    ssName: 'MUTHURAJ',
    ssPhone: '8925975896',
    cssName: 'GURUMOORTHY',
    cssPhone: '8903593614',
  },
  {
    id: 'vr-22',
    vehicleNo: 'PUSHCART9_SOUTH',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'CHELLAMUTHU',
    driverPhone: 'N/A',
    zone: 'South Zone',
    ward: 'Ward 88',
    assignedWards: ['Ward 88'],
    assignedStreets: ['NAGAMMA NAYAGAR VEEDHI'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 120,
    coveredHouseholds: 120,
    coveragePercentage: 100,
    distanceCoveredKm: 3.8,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.15,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'ZAHEER HUSSAIN',
    siPhone: '7339404132',
    ssName: 'MUTHURAJ',
    ssPhone: '8925975896',
    cssName: 'GURUMOORTHY',
    cssPhone: '8903593614',
  },
  {
    id: 'vr-23',
    vehicleNo: 'PUSHCART10_SOUTH',
    type: 'Push Cart (PTC)',
    capacity: '120 kg',
    driverName: 'MAGENDRAN',
    driverPhone: 'N/A',
    zone: 'South Zone',
    ward: 'Ward 88',
    assignedWards: ['Ward 88'],
    assignedStreets: ['ALAGAACHI THOTTAM'],
    shiftTiming: '06:00 AM - 01:00 PM',
    targetHouseholds: 140,
    coveredHouseholds: 140,
    coveragePercentage: 100,
    distanceCoveredKm: 4.0,
    tripsToDumpYard: 1,
    totalPayloadTons: 0.18,
    fuelOrBattery: 100,
    gpsStatus: 'RFID Active',
    status: 'In Service',
    siName: 'ZAHEER HUSSAIN',
    siPhone: '7339404132',
    ssName: 'MUTHURAJ',
    ssPhone: '8925975896',
    cssName: 'GURUMOORTHY',
    cssPhone: '8903593614',
  },
  {
    id: 'vr-24',
    vehicleNo: 'TN66PO982',
    type: 'Tata Ace',
    capacity: '1.2 T',
    driverName: 'SATHYA',
    driverPhone: 'N/A',
    zone: 'South Zone',
    ward: 'Ward 88',
    assignedWards: ['Ward 88'],
    assignedStreets: ['MUTHUSAMY SERKAI VEEDHI'],
    shiftTiming: '06:00 AM - 02:00 PM',
    targetHouseholds: 150,
    coveredHouseholds: 150,
    coveragePercentage: 100,
    distanceCoveredKm: 12.5,
    tripsToDumpYard: 2,
    totalPayloadTons: 1.0,
    fuelOrBattery: 88,
    gpsStatus: 'GPS Live (14 km/h)',
    status: 'In Service',
    siName: 'ZAHEER HUSSAIN',
    siPhone: '7339404132',
    ssName: 'MUTHURAJ',
    ssPhone: '8925975896',
    cssName: 'GURUMOORTHY',
    cssPhone: '8903593614',
  }
];

export function getVehicleReportItems(): VehicleReportItem[] {
  return REAL_QR_VEHICLE_REPORTS;
}
